[extend]
useDefault = true

[allowlist]
paths = [
    '''\.secrets\.baseline''',
    '''tests/cases/diff/algorithm/algorithm_004_fragment_markdown_section\.yaml''',
    '''tests/cases/diff/docker/docker_039_compose_secrets\.yaml''',
    '''tests/cases/diff/fragments/fragments_018_config_yaml_top_level_keys\.yaml''',
    '''tests/cases/diff/kubernetes/kubernetes_006_secret_reference\.yaml''',
    '''tests/cases/diff/kubernetes/kubernetes_018_image_pull_secret\.yaml''',
    '''tests/cases/diff/kubernetes/kubernetes_029_network_policy_ingress\.yaml''',
    '''tests/cases/diff/python/python_018_dunder_add_operator\.yaml''',
    '''tests/cases/diff/terraform/terraform_079_kms_key\.yaml''',
    '''tests/cases/diff/fragments/fragments_019_config_toml_sections\.yaml''',
    '''tests/cases/diff/fragments/fragments_020_config_json_top_level_keys\.yaml''',
    '''tests/cases/diff/helm/helm_025_template_secret\.yaml''',
    '''tests/cases/diff/kubernetes/kubernetes_002_replicas_change\.yaml''',
]
