from __future__ import annotations

import logging
import re
from pathlib import Path

from ..tokens import count_tokens
from ..tree import KNOWN_BINARY_EXTENSIONS
from .config import LIMITS
from .fragments import fragment_file  # type: ignore[attr-defined]
from .git import CatFileBatch, GitError
from .types import Fragment, FragmentId, extract_identifiers

logger = logging.getLogger(__name__)

# Access show_file_at_revision via module to support monkeypatching in tests
from . import git as _git  # noqa: E402

_OVERHEAD_PER_FRAGMENT = LIMITS.overhead_per_fragment
_MAX_GENERATED_FRAGMENTS = LIMITS.max_generated_fragments
_MAX_GENERATED_LINES = LIMITS.max_generated_lines

_BINARY_CTRL_RE = re.compile(r"[\x00-\x08\x0e-\x1f]")

_GENERATED_FILENAME_PATTERNS = frozenset(
    {
        ".pb.go",
        "_pb2.py",
        "_pb2_grpc.py",
        ".pb.h",
        ".pb.cc",
        ".pb.swift",
        ".min.js",
        ".min.css",
        ".designer.cs",
        ".api",
    }
)

_GENERATED_FILENAME_SUFFIXES = ("_generated.", "OuterClass.java")

_GENERATED_PATH_SEGMENTS = frozenset(
    {
        "generated",
        "gen-java",
        "gen-go",
        "gen-py",
        "gen-cpp",
        "gen-swift",
        "__generated__",
        "autogen",
        "codegen",
    }
)

_GENERATED_CONTENT_MARKERS = (
    "@generated",
    "do not edit",
    "code generated",
    "auto-generated",
    "this file is generated",
    "generated by",
    "automatically generated",
    "auto generated",
)


def _looks_binary(content: str) -> bool:
    return bool(_BINARY_CTRL_RE.search(content[:8192]))


def _show_at_revision(root_dir: Path, rev: str, rel: Path, batch_reader: CatFileBatch | None) -> str:
    if batch_reader is not None:
        return batch_reader.get(rev, rel)
    return _git.show_file_at_revision(root_dir, rev, rel)


def _read_file_content(
    file_path: Path,
    root_dir: Path,
    preferred_revs: list[str],
    batch_reader: CatFileBatch | None = None,
) -> str | None:
    from .universe import _normalize_path

    if file_path.suffix.lower() in KNOWN_BINARY_EXTENSIONS:
        return None

    abs_path = _normalize_path(file_path, root_dir)
    try:
        rel = abs_path.relative_to(root_dir.resolve())
    except ValueError:
        logger.debug("diffctx: path %s not under root %s", abs_path, root_dir)
        return None

    for rev in preferred_revs:
        try:
            content = _show_at_revision(root_dir, rev, rel, batch_reader)
            if _looks_binary(content):
                return None
            return content
        except GitError:
            continue

    if abs_path.exists() and abs_path.is_file():
        try:
            content = abs_path.read_text(encoding="utf-8")
            if _looks_binary(content):
                return None
            return content
        except (OSError, UnicodeDecodeError):
            pass

    return None


def _has_generated_filename(name: str) -> bool:
    return any(name.endswith(p) for p in _GENERATED_FILENAME_PATTERNS) or any(
        name.endswith(s) for s in _GENERATED_FILENAME_SUFFIXES
    )


def _has_generated_path_segment(path: Path) -> bool:
    return any(part.lower() in _GENERATED_PATH_SEGMENTS for part in path.parts)


def _has_generated_content_marker(content: str) -> bool:
    header_lower = "\n".join(content.splitlines()[:10]).lower()
    for marker in _GENERATED_CONTENT_MARKERS:
        if marker not in header_lower:
            continue
        if marker != "@generated":
            return True
        if re.search(r"@generated(?![a-z])", header_lower):
            return True
    return False


def _is_generated_file(path: Path, content: str) -> bool:
    return _has_generated_filename(path.name) or _has_generated_path_segment(path) or _has_generated_content_marker(content)


def _truncate_generated_fragments(file_frags: list[Fragment]) -> list[Fragment]:
    truncated: list[Fragment] = []
    for frag in file_frags:
        if frag.line_count <= _MAX_GENERATED_LINES:
            truncated.append(frag)
            continue
        lines = frag.content.splitlines()
        remaining = len(lines) - _MAX_GENERATED_LINES
        lines = lines[:_MAX_GENERATED_LINES]
        truncated_content = "\n".join(lines) + f"\n# ... [{remaining} more lines]"
        truncated.append(
            Fragment(
                id=FragmentId(frag.path, frag.start_line, frag.start_line + len(lines) - 1),
                kind=frag.kind,
                content=truncated_content,
                identifiers=extract_identifiers(truncated_content),
            )
        )
    return truncated


def _dedup_fragments(raw_frags: list[Fragment]) -> list[Fragment]:
    seen: set[FragmentId] = set()
    result: list[Fragment] = []
    for f in raw_frags:
        if f.id not in seen:
            result.append(f)
            seen.add(f.id)
    return result


def _cap_fragments(file_frags: list[Fragment], cap: int, file_path: Path, is_generated: bool) -> list[Fragment]:
    if len(file_frags) <= cap:
        return file_frags
    file_frags.sort(key=lambda f: f.line_count, reverse=True)
    file_frags = file_frags[:cap]
    logger.debug(
        "diffctx: capped %s to %d fragments%s",
        file_path.name,
        cap,
        " (generated)" if is_generated else "",
    )
    return file_frags


def _process_files_for_fragments(
    files: list[Path],
    root_dir: Path,
    preferred_revs: list[str],
    seen_frag_ids: set[FragmentId],
    batch_reader: CatFileBatch | None = None,
) -> list[Fragment]:
    max_frags = LIMITS.max_fragments
    fragments: list[Fragment] = []
    for file_path in files:
        content = _read_file_content(file_path, root_dir, preferred_revs, batch_reader)
        if content is None:
            continue
        raw_frags = [f for f in fragment_file(file_path, content) if f.id not in seen_frag_ids]
        file_frags = _dedup_fragments(raw_frags)

        is_generated = _is_generated_file(file_path, content)
        cap = _MAX_GENERATED_FRAGMENTS if is_generated else max_frags
        file_frags = _cap_fragments(file_frags, cap, file_path, is_generated)

        if is_generated:
            file_frags = _truncate_generated_fragments(file_frags)

        for frag in file_frags:
            fragments.append(frag)
            seen_frag_ids.add(frag.id)
    return fragments


def _create_whole_file_fragment(
    path: Path,
    root_dir: Path,
    preferred_revs: list[str],
    batch_reader: CatFileBatch | None = None,
) -> Fragment | None:
    content = _read_file_content(path, root_dir, preferred_revs, batch_reader)
    if not content or not content.strip():
        return None
    if _is_generated_file(path, content):
        lines = content.splitlines()
        if len(lines) > _MAX_GENERATED_LINES:
            remaining = len(lines) - _MAX_GENERATED_LINES
            content = "\n".join(lines[:_MAX_GENERATED_LINES]) + f"\n# ... [{remaining} more lines]"
    lines = content.splitlines()
    frag = Fragment(
        id=FragmentId(path=path, start_line=1, end_line=len(lines)),
        kind="chunk",
        content=content,
        identifiers=extract_identifiers(content),
    )
    frag.token_count = count_tokens(content).count + _OVERHEAD_PER_FRAGMENT
    return frag
