from __future__ import annotations

EXTENSION_TO_LANGUAGE: dict[str, str] = {
    ".py": "python",
    ".pyw": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".jsx": "jsx",
    ".ts": "typescript",
    ".tsx": "tsx",
    ".mts": "typescript",
    ".cts": "typescript",
    ".json": "json",
    ".yaml": "yaml",
    ".yml": "yaml",
    ".toml": "toml",
    ".md": "markdown",
    ".markdown": "markdown",
    ".html": "html",
    ".htm": "html",
    ".css": "css",
    ".scss": "scss",
    ".sass": "sass",
    ".less": "less",
    ".xml": "xml",
    ".svg": "xml",
    ".sh": "bash",
    ".bash": "bash",
    ".zsh": "zsh",
    ".fish": "fish",
    ".ps1": "powershell",
    ".psm1": "powershell",
    ".bat": "batch",
    ".cmd": "batch",
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".cs": "csharp",
    ".fs": "fsharp",
    ".fsx": "fsharp",
    ".java": "java",
    ".kt": "kotlin",
    ".kts": "kotlin",
    ".scala": "scala",
    ".sc": "scala",
    ".go": "go",
    ".rs": "rust",
    ".rb": "ruby",
    ".rake": "ruby",
    ".gemspec": "ruby",
    ".php": "php",
    ".swift": "swift",
    ".m": "objectivec",
    ".mm": "objectivec",
    ".r": "r",
    ".R": "r",
    ".lua": "lua",
    ".pl": "perl",
    ".pm": "perl",
    ".ex": "elixir",
    ".exs": "elixir",
    ".erl": "erlang",
    ".hrl": "erlang",
    ".hs": "haskell",
    ".lhs": "haskell",
    ".ml": "ocaml",
    ".mli": "ocaml",
    ".clj": "clojure",
    ".cljs": "clojure",
    ".cljc": "clojure",
    ".sql": "sql",
    ".graphql": "graphql",
    ".gql": "graphql",
    ".proto": "protobuf",
    ".dockerfile": "dockerfile",
    ".tf": "terraform",
    ".hcl": "hcl",
    ".vim": "vim",
    ".el": "elisp",
    ".lisp": "lisp",
    ".scm": "scheme",
    ".rkt": "racket",
    ".zig": "zig",
    ".nim": "nim",
    ".v": "v",
    ".sv": "systemverilog",
    ".vhd": "vhdl",
    ".vhdl": "vhdl",
    ".d": "d",
    ".dart": "dart",
    ".groovy": "groovy",
    ".gradle": "groovy",
    ".jl": "julia",
    ".ini": "ini",
    ".cfg": "ini",
    ".conf": "ini",
    ".properties": "properties",
    ".env": "dotenv",
    ".gitignore": "gitignore",
    ".dockerignore": "gitignore",
    ".editorconfig": "editorconfig",
    ".tex": "latex",
    ".latex": "latex",
    ".rst": "rst",
    ".txt": "text",
    ".log": "text",
    ".diff": "diff",
    ".patch": "diff",
    ".vue": "vue",
    ".svelte": "svelte",
}

FILENAME_TO_LANGUAGE: dict[str, str] = {
    "makefile": "makefile",
    "gnumakefile": "makefile",
    "dockerfile": "dockerfile",
    "containerfile": "dockerfile",
    "vagrantfile": "ruby",
    "gemfile": "ruby",
    "rakefile": "ruby",
    "guardfile": "ruby",
    "brewfile": "ruby",
    "podfile": "ruby",
    "cmakelists.txt": "cmake",
    "justfile": "just",
    ".bashrc": "bash",
    ".bash_profile": "bash",
    ".bash_aliases": "bash",
    ".zshrc": "zsh",
    ".zshenv": "zsh",
    ".zprofile": "zsh",
    ".profile": "bash",
    ".gitconfig": "gitconfig",
    ".gitattributes": "gitattributes",
    ".gitignore": "gitignore",
    ".dockerignore": "gitignore",
    ".treemapperignore": "gitignore",
    ".npmrc": "ini",
    ".yarnrc": "yaml",
    ".prettierrc": "json",
    ".eslintrc": "json",
    "package.json": "json",
    "tsconfig.json": "json",
    "composer.json": "json",
    "cargo.toml": "toml",
    "pyproject.toml": "toml",
    "go.mod": "gomod",
    "go.sum": "gosum",
    "requirements.txt": "text",
    "pipfile": "toml",
    "procfile": "text",
    "jenkinsfile": "groovy",
}

# Tree-sitter specific language codes (some differ from display names)
TREE_SITTER_LANGUAGES: dict[str, str] = {
    ".py": "python",
    ".pyw": "python",
    ".pyi": "python",
    ".js": "javascript",
    ".jsx": "javascript",
    ".mjs": "javascript",
    ".cjs": "javascript",
    ".ts": "typescript",
    ".tsx": "typescript",
    ".mts": "typescript",
    ".cts": "typescript",
    ".go": "go",
    ".rs": "rust",
    ".java": "java",
    ".c": "c",
    ".h": "c",
    ".cpp": "cpp",
    ".hpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".rb": "ruby",
    ".rake": "ruby",
    ".cs": "c_sharp",
}


def get_language_for_file(path: str) -> str | None:
    from pathlib import Path

    p = Path(path)
    name_lower = p.name.lower()

    if name_lower in FILENAME_TO_LANGUAGE:
        return FILENAME_TO_LANGUAGE[name_lower]

    suffix = p.suffix.lower()
    if suffix:
        return EXTENSION_TO_LANGUAGE.get(suffix)

    if name_lower.startswith("dockerfile"):
        return "dockerfile"

    return None
