from __future__ import annotations

import keyword
from collections.abc import Iterable
from pathlib import Path
from typing import ClassVar

from .constants import CODE_EXTENSIONS, DOC_EXTENSIONS

PY_KEYWORDS: frozenset[str] = frozenset(k.lower() for k in keyword.kwlist)

_CODE_STOPWORDS: frozenset[str] = frozenset(
    {
        # Placeholders and comments
        "todo",
        "fixme",
        "note",
        "hack",
        "xxx",
        "foo",
        "bar",
        "baz",
        "qux",
        "tmp",
        "temp",
        # Python-specific
        "self",
        "cls",
        # Generic CRUD verbs (too ubiquitous for concept matching)
        "get",
        "set",
        "put",
        "delete",
        "remove",
        "update",
        "create",
        "read",
        "write",
        "open",
        "close",
        "start",
        "stop",
        "run",
        "execute",
        "call",
        "invoke",
        "handle",
        "process",
        "validate",
        "check",
        "test",
        "init",
        "setup",
        "teardown",
        "load",
        "save",
        "parse",
        "format",
        "convert",
        "transform",
        "render",
        "build",
        "make",
        "copy",
        "clone",
        "reset",
        "clear",
        "flush",
        "send",
        "receive",
        "emit",
        "insert",
        "append",
        "extend",
        "split",
        "join",
        "trim",
        "strip",
        "contains",
        "includes",
        "push",
        "pop",
        "concat",
        "slice",
        "each",
        "print",
        "println",
        "printf",
        "sprintf",
        "fprintf",
        "abort",
        "retry",
        "apply",
        "resolve",
        "reject",
        "defer",
        "sleep",
        "wait",
        "poll",
        "encode",
        "decode",
        "encrypt",
        "decrypt",
        "hash",
        "sign",
        "verify",
        "register",
        "unregister",
        "mount",
        "unmount",
        "enable",
        "disable",
        "show",
        "hide",
        "lock",
        "unlock",
        "acquire",
        "release",
        "commit",
        "rollback",
        "begin",
        "end",
        # Generic variable/parameter names
        "value",
        "values",
        "result",
        "results",
        "item",
        "items",
        "element",
        "elements",
        "key",
        "keys",
        "text",
        "num",
        "number",
        "count",
        "index",
        "idx",
        "size",
        "length",
        "len",
        "array",
        "dict",
        "obj",
        "object",
        "args",
        "kwargs",
        "params",
        "options",
        "err",
        "error",
        "errors",
        "msg",
        "message",
        "messages",
        "log",
        "logger",
        "debug",
        "info",
        "warn",
        "warning",
        "func",
        "function",
        "method",
        "callback",
        "handler",
        "listener",
        "event",
        "events",
        "request",
        "response",
        "req",
        "res",
        "body",
        "header",
        "headers",
        "query",
        "param",
        "id",
        "uid",
        "uuid",
        # Language keywords (cross-language syntax)
        "var",
        "let",
        "const",
        "new",
        "this",
        "null",
        "nil",
        "none",
        "void",
        "true",
        "false",
        "static",
        "final",
        "abstract",
        "virtual",
        "override",
        "public",
        "private",
        "protected",
        "internal",
        "extern",
        "inline",
        "volatile",
        "mutable",
        "readonly",
        "super",
        "extends",
        "implements",
        "import",
        "export",
        "require",
        "include",
        "using",
        "typedef",
        "define",
        "ifdef",
        "ifndef",
        "endif",
        "elif",
        "else",
        "case",
        "switch",
        "break",
        "continue",
        "return",
        "goto",
        "sizeof",
        "typeof",
        "instanceof",
        "throw",
        "throws",
        "try",
        "catch",
        "finally",
        "raise",
        "except",
        "yield",
        "lambda",
        "proc",
        "sub",
        "def",
        "async",
        "await",
        # Primitive types
        "int",
        "uint",
        "long",
        "float",
        "double",
        "char",
        "byte",
        "short",
        "signed",
        "unsigned",
        "bool",
        "boolean",
        "string",
        "str",
        "size_t",
        "usize",
        "isize",
        "int8",
        "int16",
        "int32",
        "int64",
        "uint8",
        "uint16",
        "uint32",
        "uint64",
        "float32",
        "float64",
        # Python dunder methods
        "__init__",
        "__main__",
        "__name__",
        "__str__",
        "__repr__",
        "__eq__",
        "__hash__",
        "__len__",
        "__iter__",
        "__next__",
        "__enter__",
        "__exit__",
        # Shell builtins
        "echo",
        "done",
        "local",
        "eval",
        "exec",
        "exit",
        "trap",
        "bash",
        "then",
        "esac",
        "fi",
        "do",
        "for",
        "while",
        "until",
        "shift",
        "unset",
        "declare",
        "alias",
        # Markup/CSS (zero discriminative value in diffs)
        "html",
        "head",
        "div",
        "span",
        "form",
        "button",
        "img",
        "href",
        "style",
        "display",
        "margin",
        "padding",
        "border",
        "color",
        "width",
        "height",
        "flex",
        "grid",
        "onclick",
        "onchange",
        "onsubmit",
        "classname",
    }
)

_DOMAIN_STOPWORDS: frozenset[str] = frozenset(
    {
        # Generic verbs (too ubiquitous for concept matching)
        "add",
        "sort",
        "filter",
        "find",
        "select",
        "merge",
        "match",
        "replace",
        "dispatch",
        "notify",
        "subscribe",
        "publish",
        "connect",
        "disconnect",
        "bind",
        "listen",
        "accept",
        "every",
        "some",
        "reduce",
        "splice",
        "unshift",
        "throw",
        "catch",
        "create",
        "destroy",
        "dispose",
        "finalize",
        # Generic variable/parameter names
        "data",
        "name",
        "names",
        "list",
        "map",
        "config",
        "settings",
        "context",
        "ctx",
        "state",
        "status",
        "type",
        "kind",
        "mode",
        "flag",
        "flags",
        "path",
        "file",
        "dir",
        "url",
        "uri",
        "host",
        "port",
        "input",
        "output",
        "source",
        "target",
        "dest",
        "src",
        "dst",
        "user",
        "users",
        "model",
        "models",
        "view",
        "views",
        "service",
        "services",
        "client",
        "server",
        "api",
        "app",
        "main",
        "util",
        "utils",
        "helper",
        "helpers",
        "common",
        "base",
        "core",
        "default",
        "defaults",
        "version",
        "label",
        "labels",
        "tag",
        "tags",
        "level",
        "scope",
        "token",
        "tokens",
        "task",
        "tasks",
        "job",
        "jobs",
        "step",
        "steps",
        "stage",
        "cache",
        "timeout",
        "interval",
        "duration",
        "timestamp",
        "channel",
        "buffer",
        "queue",
        "stack",
        "heap",
        "node",
        "nodes",
        "edge",
        "edges",
        "child",
        "children",
        "parent",
        "root",
        "leaf",
        "link",
        "ref",
        "reference",
        "instance",
        "schema",
        "table",
        "column",
        "row",
        "field",
        "record",
        "entry",
        "spec",
        "env",
        "namespace",
        "prefix",
        "suffix",
        "pattern",
        "template",
        "factory",
        "builder",
        "adapter",
        "proxy",
        "wrapper",
        "manager",
        "controller",
        "provider",
        "consumer",
        "producer",
        "worker",
        "pool",
        "connection",
        "session",
        "stream",
        "pipe",
        "socket",
        "signal",
        "trigger",
        "action",
        "command",
        "rule",
        "rules",
        "policy",
        "strategy",
        "middleware",
        "plugin",
        "module",
        "package",
        "component",
        "container",
        "registry",
        "repository",
        # OOP keywords
        "interface",
        "struct",
        "enum",
        "union",
        "trait",
        "impl",
        "class",
        "implement",
        "inherit",
        "mixin",
        "tostring",
        "hashcode",
        "equals",
        # React hooks
        "usestate",
        "useeffect",
        "usecontext",
        "usereducer",
        "usecallback",
        "usememo",
        "useref",
        "uselayouteffect",
        "useimperativehandle",
        "usedebugvalue",
        "useid",
        "usetransition",
        "usedeferredvalue",
        "createcontext",
        "forwardref",
        "createref",
        "suspense",
        "strictmode",
        "profiler",
        # React Router hooks
        "usenavigate",
        "useparams",
        "uselocation",
        "usesearchparams",
        "useloaderdata",
        "useactiondata",
        "usefetcher",
        "useoutletcontext",
        # Redux hooks
        "usedispatch",
        "useselector",
        "usestore",
        # React Query hooks
        "usequery",
        "usemutation",
        "usesubscription",
        # Vue composition API
        "definecomponent",
        "defineprops",
        "defineemits",
        "defineslots",
        "definemodel",
        "defineexpose",
        "toref",
        "torefs",
        "reactive",
        "computed",
        "onmounted",
        "onunmounted",
        "onbeforemount",
        "onupdated",
        "watcheffect",
        "nexttick",
        # Angular lifecycle
        "ngoninit",
        "ngondestroy",
        "ngonchanges",
        "ngafterviewinit",
        # JavaScript / Web / DOM
        "console",
        "document",
        "window",
        "navigator",
        "location",
        "history",
        "fetch",
        "promise",
        "undefined",
        "prototype",
        "constructor",
        "exports",
        "props",
        "effect",
        "memo",
        "styles",
        "innerhtml",
        "textcontent",
        "appendchild",
        "createelement",
        "queryselector",
        "getelementbyid",
        "addeventlistener",
        # IaC / Terraform / Kubernetes / Cloud
        "resource",
        "variable",
        "locals",
        "terraform",
        "jsonencode",
        "cidr",
        "subnet",
        "ingress",
        "egress",
        "protocol",
        "cidr_blocks",
        "security_group",
        "arn",
        "vpc",
        "aws",
        "gcp",
        "azure",
        "region",
        "zone",
        "cluster",
        "replicas",
        "selector",
        "metadata",
        "annotations",
        "volumes",
        "ports",
        "image",
        "containers",
        "resources",
        "limits",
        "requests",
        "apiversion",
        "configmap",
        "secret",
        "deployment",
        "statefulset",
        "daemonset",
        "cronjob",
        "serviceaccount",
        "role",
        "rolebinding",
        "clusterrole",
        # CI/CD
        "install",
        "deploy",
        "pipeline",
        "script",
        "pull",
        "uses",
        "with",
        "needs",
        "runs",
        "checkout",
        "artifact",
        "artifacts",
        "workflow",
        "schedule",
        "cron",
        "branch",
        "branches",
        "release",
        # Docker
        "from",
        "workdir",
        "expose",
        "entrypoint",
        "volume",
        "arg",
        "healthcheck",
        "stopsignal",
        # Testing
        "describe",
        "it",
        "expect",
        "assert",
        "should",
        "mock",
        "stub",
        "spy",
        "before",
        "after",
        "beforeall",
        "afterall",
        "beforeeach",
        "aftereach",
        "suite",
        "fixture",
        "given",
        "when",
        # SQL / Database
        "insert",
        "update",
        "delete",
        "from",
        "where",
        "join",
        "inner",
        "outer",
        "left",
        "right",
        "group",
        "order",
        "limit",
        "offset",
        "having",
        "distinct",
        "count",
        "sum",
        "avg",
        "min",
        "max",
        "constraint",
        "primary",
        "foreign",
        "unique",
        "not",
        "and",
        "or",
        "between",
        "exists",
        "values",
        "into",
        "alter",
        "drop",
        "truncate",
        "grant",
        "revoke",
        # Markup (additional)
        "body",
        "title",
        "meta",
        "script",
        "label",
        "select",
        "option",
        "thead",
        "tbody",
        "class",
        "type",
        "name",
        "value",
        "placeholder",
        "required",
        "disabled",
        "checked",
        "selected",
        "hidden",
        # Networking / HTTP
        "http",
        "https",
        "tcp",
        "udp",
        "dns",
        "ssl",
        "tls",
        "cert",
        "certificate",
        "content",
        "authorization",
        "bearer",
        "basic",
        "digest",
        "origin",
        "referer",
        "cookie",
        "cookies",
        "redirect",
        "gateway",
        "load",
        "balance",
        "upstream",
        "downstream",
        "endpoint",
        "route",
        "routes",
        "router",
        "method",
        "code",
        # Language names and runtime identifiers
        "java",
        "python",
        "golang",
        "ruby",
        "rust",
        "swift",
        "kotlin",
        "scala",
        "perl",
        "elixir",
        "haskell",
        "clojure",
        "erlang",
        "typescript",
        "javascript",
        "csharp",
        "cplusplus",
        "alpine",
        "ubuntu",
        "debian",
        "linux",
        "darwin",
        "windows",
        # Standard library / type names
        "time",
        "math",
        "system",
        "vector",
        "hashmap",
        "hashset",
        "treemap",
        "arraylist",
        "linkedlist",
        "optional",
        "future",
        "pair",
        "tuple",
        "collection",
        "collections",
        "iterator",
        "iterable",
        "comparable",
        "serializable",
        "cloneable",
        "runnable",
        "callable",
        "supplier",
        "predicate",
        "comparator",
        "json",
        "xml",
        "yaml",
        "toml",
        "csv",
        # Common domain terms
        "email",
        "phone",
        "address",
        "date",
        "datetime",
        "password",
        "username",
        "auth",
        "login",
        "logout",
        "admin",
        "account",
        "profile",
        "permission",
        "team",
        "organization",
        "project",
        "description",
        "category",
        "comment",
        "comments",
        "like",
        "share",
        "search",
        "page",
        "pages",
        "upload",
        "download",
        "notification",
        "notifications",
        "alert",
        "alerts",
        "validation",
        "production",
        "staging",
        "development",
        "testing",
        "localhost",
        "unknown",
        "refs",
        "heads",
        "remote",
        "master",
        "rebase",
        "cherry",
        "stash",
    }
)

CODE_STOPWORDS: frozenset[str] = _CODE_STOPWORDS | PY_KEYWORDS | _DOMAIN_STOPWORDS

_DOCS_STOPWORDS: frozenset[str] = frozenset(
    {
        "the",
        "and",
        "for",
        "that",
        "with",
        "this",
        "from",
        "has",
        "have",
        "not",
        "are",
        "was",
        "were",
        "will",
        "can",
        "you",
        "all",
        "any",
        "but",
        "they",
        "their",
        "there",
        "than",
        "then",
        "when",
        "what",
        "which",
        "about",
        "after",
        "also",
        "been",
        "before",
        "between",
        "both",
        "could",
        "each",
        "even",
        "into",
        "its",
        "just",
        "more",
        "most",
        "other",
        "over",
        "same",
        "should",
        "some",
        "such",
        "through",
        "very",
        "well",
        "would",
        "use",
        "using",
        "used",
        "may",
        "must",
        "only",
        "within",
        "without",
        "new",
        "old",
        "one",
        "two",
        "three",
        "first",
        "last",
        "next",
        "many",
        "example",
        "note",
        "see",
        "get",
        "set",
        "add",
        "like",
        "need",
        "heading",
        "section",
        "content",
        "long",
        "under",
        "value",
        "field",
        "name",
        "type",
        "page",
        "text",
        "data",
        "item",
        "list",
        "file",
        "code",
        "function",
        "class",
        "method",
        "return",
        "where",
        "how",
        "why",
        "output",
        "input",
        "result",
        "error",
        "default",
        "true",
        "false",
    }
)


class TokenProfile:
    CODE = "code"
    DOCS = "docs"
    LEGAL = "legal"
    DATA = "data"
    GENERIC = "generic"

    _PROFILES: ClassVar[dict[str, tuple[frozenset[str], int]]] = {
        CODE: (CODE_STOPWORDS, 3),
        DOCS: (_DOCS_STOPWORDS, 3),
        LEGAL: (frozenset(), 4),
        DATA: (frozenset(), 2),
        GENERIC: (CODE_STOPWORDS, 3),
    }

    @classmethod
    def get_stopwords(cls, profile: str) -> frozenset[str]:
        return cls._PROFILES.get(profile, cls._PROFILES[cls.GENERIC])[0]

    @classmethod
    def get_min_len(cls, profile: str) -> int:
        return cls._PROFILES.get(profile, cls._PROFILES[cls.GENERIC])[1]

    @classmethod
    def from_path(cls, path_str: str) -> str:
        p = Path(path_str)
        suffix = p.suffix.lower()
        name_lower = p.name.lower()

        if suffix in CODE_EXTENSIONS:
            return cls.CODE

        if suffix in DOC_EXTENSIONS or suffix in {".markdown", ".tex"}:
            return cls.DOCS

        data_exts = {".csv", ".json", ".jsonl", ".yaml", ".yml", ".toml", ".xml", ".ini", ".env"}
        if suffix in data_exts:
            return cls.DATA

        legal_names = {"license", "licence", "legal", "terms", "agreement", "contract", "policy", "privacy", "tos", "eula"}
        stem = p.stem.lower()
        if stem in legal_names or any(lw in name_lower for lw in ("license", "legal", "terms")):
            return cls.LEGAL

        return cls.GENERIC


def is_reasonable_ident(ident: str, *, min_len: int = 3, profile: str = "code") -> bool:
    if not ident or len(ident) < min_len:
        return False
    low = ident.lower()
    stopwords = TokenProfile.get_stopwords(profile)
    if low in stopwords:
        return False
    if low.isdigit():
        return False
    return True


def filter_idents(idents: Iterable[str], *, min_len: int = 3, profile: str = "code") -> list[str]:
    return [s for s in idents if is_reasonable_ident(s, min_len=min_len, profile=profile)]
