name: TreeMapper CI

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-22.04, macos-latest, windows-latest]
        python-version: [3.9, '3.10', '3.11']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.cfg') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: Build with PyInstaller
        run: |
          python -m PyInstaller --clean -y --dist ./dist/${{ runner.os }} --workpath /tmp treemapper.spec

      - name: Build with python -m build
        run: |
          python -m build

      - name: Run Tests
        run: |
          pytest

  test-pypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [pypy-3.9]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PyPy ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pypy-pip-${{ hashFiles('**/setup.cfg') }}
          restore-keys: |
            pypy-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install build pytest

      - name: Build with python -m build
        run: |
          python -m build

      - name: Run Tests
        run: |
          pytest